// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function Theme() {
  return window['go']['main']['App']['Theme']();
}
